@ECHO OFF

rem This is a simple batch file to create 200 local user accounts for use when testing password spraying attacks.
rem by Beau Bullock (@dafthack)

net user Robert !QAZ1qaz /add
net user Christian 0EmWSTm2ir /add
net user Frances 0kW09PF0ed /add
net user Jacqueline 0MfhUNrRuh /add
net user Sandra 0MjhDXjaDJ /add
net user Ralph 10NcstCcPt /add
net user Jason 13Ugj7Hhji /add
net user Albert 14C2MnFyHg /add
net user Jane 15sAfeSyqN /add
net user Amanda 1CqgIcwZe9 /add
net user George 1IeZwWMjGx /add
net user Barbara 2020Spring /add
net user Victoria 2DEFaJB4Nf /add
net user Amy 2mLmSeZpUH /add
net user Kimberly 3aQXCw4ynu /add
net user Samantha 3Y3NpCqFmH /add
net user Nancy 4Io4LVWeyj /add
net user Amber 4jTdbeRM6s /add
net user Deborah 4w4elsNn0p /add
net user Jennifer 51pVKpvv8M /add
net user Nicholas 5s7IWLmuCO /add
net user Teresa 5w5EENjlkZ /add
net user Howard 6pAam9UErg /add
net user Jacob 6rqehWmLah /add
net user Steven 72k5MMr93A /add
net user Ronald 7BAsaCRDsf /add
net user Ashley 7dSjnsYqNG /add
net user Timothy 7fqYR3qOBJ /add
net user Sara 7JKKepVWvm /add
net user Jose 7mUsCwODiR /add
net user Harold 7oeWNZvENd /add
net user Ruth 8mdDbfrV6v /add
net user Keith 8VTODSDiqR /add
net user Jean 9evuiuEtVW /add
net user Anthony Acme1234 /add
net user Donald Acme2020 /add
net user Karen aMg9EjYBMR /add
net user Adam AyFLpvG2Wn /add
net user Grace b7UZmcDleD /add
net user Bobby bbsRWNlWdd /add
net user Roger bFgxTuUKt0 /add
net user Austin Bl8fOaT0Yv /add
net user Evelyn bNHohrNAi7 /add
net user Brandon c3cEbIDPCP /add
net user Kyle COjAvIN2BU /add
net user Joshua CoN3Wq2j4L /add
net user David correcthorse/add
net user Raymond CqUwPv4FaX /add
net user Gabriel D5qkE4gWBu /add
net user Emma D6jCcTdu9X /add
net user Margaret dKrVYwiYZm /add
net user Maria dn62wstfGS /add
net user Louis dtAeTbk1H9 /add
net user Bruce E5YGbwFQnf /add
net user Julie e7XjcPfhKk /add
net user Larry eb2l1N7vQH /add
net user Vincent eBOOubrlCS /add
net user Brian EBPx2Jxqpt /add
net user Lawrence ECuIE7vP1V /add
net user Emily Emily /add
net user Helen EOipi5CGw0 /add
net user Juan f6TxdHLnhc /add
net user Henry Fall2020 /add
net user Heather fkSnWjAGog /add
net user Patricia FM5ty2ybpa /add
net user Randy gJ0okiDnQz /add
net user Tiffany GkERsy4vXo /add
net user Stephen gouXm65aYY /add
net user Gerald GsNyXDpLW8 /add
net user Jessica H1BymbLCsc /add
net user Beau HackNaked /add
net user Marilyn Hek4DiGUR7 /add
net user Walter hHpl5h5v6P /add
net user Alan hpPBy2KauU /add
net user Jesse hXYCoTVBLu /add
net user John IHateClowns /add
net user Russell IvgNosGUPI /add
net user Eric jz3sp5OWko /add
net user Laura JzqB1D5yCA /add
net user Wayne K93EP0DHOi /add
net user Jeremy k99iQy5xrm /add
net user Eugene kaA9wTgxja /add
net user Willie kXnztl9Tbb /add
net user Nicole l6utL7CfgB /add
net user Kelly L89yPw2lYq /add
net user Patrick LetMeIn /add
net user Joe lFExJfKRUg /add
net user Gloria LG8NWwD2Vr /add
net user Mark Loienvb235 /add
net user Frank lVIwKMIAaT /add
net user Danielle Mhj25BjqIM /add
net user Michelle Michelle /add
net user Olivia MwmHOXE0jH /add
net user Carl N68y1h7vnx /add
net user Diana N90cpJFRws /add
net user Zachary NabYbioqso /add
net user Megan NAsSWwYTnZ /add
net user Billy Ng3W6kQLGU /add
net user Diane NnILorQVnI /add
net user Brenda NO5IvBZaaL /add
net user Justin NotTwHAXG0 /add
net user Hannah NyRd40Xiv5 /add
net user Debra O3IUxwO11o /add
net user Harry OG1kCfWp9H /add
net user Madison oHBV93eag5 /add
net user Cheryl oKM4ll6LcU /add
net user Kenneth onkIDlrYVn /add
net user Bryan OPh0zBfpgO /add
net user Judy P71aMfWyuu /add
net user Rose p8pJJI37Dz /add
net user Johnny P9BDd9YtnG /add
net user Benjamin Pa55w0rd /add
net user Joseph Pa55word /add
net user Charles Pass1234 /add
net user Carol Pass1234 /add
net user William password /add
net user Thomas Password /add
net user James Password123 /add
net user Daniel Password123 /add
net user Alexander Password123 /add
net user Aaron Password2020 /add
net user Rachel PEXgU4pYvb /add
net user Rebecca pg4aVcGTLr /add
net user Anna PHXuvYvfk1 /add
net user Kathy PLb3pw9INs /add
net user Kathleen PMRhcfwtdL /add
net user Christine Q2aSPRvaai /add
net user Judith q9G2XIKvd2 /add
net user Jonathan QiquVYfWuf /add
net user Stephanie QODA2wzcmi /add
net user Andrew QODRv3SC4f /add
net user Lori qR7bmd1TmL /add
net user Philip quvSajbmlr /add
net user Abigail qxmCZu1djM /add
net user Ryan r506vat5ot /add
net user Dorothy RdjKE95kRq /add
net user Richard Richard /add
net user Marie RJqMajnJbQ /add
net user Angela rRdO0d9p44 /add
net user Janice Rx3JisLSWu /add
net user Jordan s6OG4h4KXH /add
net user Dylan sa1bsMEoKn /add
net user Samuel SANS2020 /add
net user Janet sbpnFv1yEW /add
net user Doris ScHKAIN9ir /add
net user Paul SecurePassword /add
net user Carolyn sgeGFAeOIC /add
net user Melissa SMmQsDtUs6 /add
net user Elizabeth Spring2020 /add
net user Susan Spring2020 /add
net user Andrea Spring2020 /add
net user Kathryn Spring2020 /add
net user Tyler Summer2020 /add
net user Linda Summer2020 /add
net user Joan Summer2020 /add
net user Christina Summer2020 /add
net user Matthew SuperSecure /add
net user Brittany suWN35uaex /add
net user Sharon tCipbqvbyP /add
net user Alice Tk3QToEnXE /add
net user Nathan tXRRH6IvMF /add
net user Edward tYkGAvZt0s /add
net user Sean U489iZYnX2 /add
net user Beverly ujyfszSA0D /add
net user Denise uKT0fF3GRd /add
net user Gary UQgaOuQIPG /add
net user Virginia urVFZ6zGwO /add
net user Terry vQ4Ic19JvA /add
net user Noah vQVuOs6Iym /add
net user Cynthia Vr2WemtvBM /add
net user Natalie vZeCcZctzR /add
net user Ann WEgEvH8Dfc /add
net user Arthur whC3lrHjop /add
net user Michael Winter2020 /add
net user Christopher Winter2020 /add
net user Gregory Winter2020 /add
net user Jack Winter2020 /add
net user Dennis Winter2020 /add
net user Jerry Winter2020 /add
net user Joyce wJWs4UIK5j /add
net user Shirley WldefkxV9Z /add
net user Betty wN3IGCMqkA /add
net user Martha wrVD8BOeCF /add
net user Mary wxMnFXdb6Y /add
net user Catherine xbWlbYF8Tx /add
net user Katherine xECiMT7KFH /add
net user Ethan XfKIR1J9nr /add
net user Jeffrey XgeObYN3jQ /add
net user Theresa XYh3aHJ2DP /add
net user Scott Y3YVdz1y1J /add
net user Pamela Y89IMqIaqP /add
net user Peter yCbzOvpUrV /add
net user Julia Ym4aoDUCyL /add
net user Sarah ypsXtGwbUi /add
net user Roy za8rDTGsf2 /add
net user Douglas zaVwMPkLVW /add
net user Lauren zeBYRNhDs0 /add
net user Mildred zGhFcwfCiw /add
net user Lisa zmn8aV5Abs /add
net user Kevin ZYYCm9ju8v /add