@ECHO off

rem This is a simple batch file to delete the users created with 200-user-gen.bat
rem BE CAREFUL NOT TO DELETE YOUR OWN USER (Search for it in this list and remove it from the script)
rem by Beau Bullock (@dafthack)

net user Robert /delete
net user Christian /delete
net user Frances /delete
net user Jacqueline /delete
net user Sandra /delete
net user Ralph /delete
net user Jason /delete
net user Albert /delete
net user Jane /delete
net user Amanda /delete
net user George /delete
net user Barbara /delete
net user Victoria /delete
net user Amy /delete
net user Kimberly /delete
net user Samantha /delete
net user Nancy /delete
net user Amber /delete
net user Deborah /delete
net user Jennifer /delete
net user Nicholas /delete
net user Teresa /delete
net user Howard /delete
net user Jacob /delete
net user Steven /delete
net user Ronald /delete
net user Ashley /delete
net user Timothy /delete
net user Sara /delete
net user Jose /delete
net user Harold /delete
net user Ruth /delete
net user Keith /delete
net user Jean /delete
net user Anthony /delete
net user Donald /delete
net user Karen /delete
net user Adam /delete
net user Grace /delete
net user Bobby /delete
net user Roger /delete
net user Austin /delete
net user Evelyn /delete
net user Brandon /delete
net user Kyle /delete
net user Joshua /delete
net user David /delete
net user Raymond /delete
net user Gabriel /delete
net user Emma /delete
net user Margaret /delete
net user Maria /delete
net user Louis /delete
net user Bruce /delete
net user Julie /delete
net user Larry /delete
net user Vincent /delete
net user Brian /delete
net user Lawrence /delete
net user Emily /delete
net user Helen /delete
net user Juan /delete
net user Henry /delete
net user Heather /delete
net user Patricia /delete
net user Randy /delete
net user Tiffany /delete
net user Stephen /delete
net user Gerald /delete
net user Jessica /delete
net user Marilyn /delete
net user Walter /delete
net user Alan /delete
net user Jesse /delete
net user John /delete
net user Russell /delete
net user Eric /delete
net user Laura /delete
net user Wayne /delete
net user Jeremy /delete
net user Eugene /delete
net user Willie /delete
net user Nicole /delete
net user Kelly /delete
net user Patrick /delete
net user Beau /delete
net user Joe /delete
net user Gloria /delete
net user Mark /delete
net user Frank /delete
net user Danielle /delete
net user Michelle /delete
net user Olivia /delete
net user Carl /delete
net user Diana /delete
net user Zachary /delete
net user Megan /delete
net user Billy /delete
net user Diane /delete
net user Brenda /delete
net user Justin /delete
net user Hannah /delete
net user Debra /delete
net user Harry /delete
net user Madison /delete
net user Cheryl /delete
net user Kenneth /delete
net user Bryan /delete
net user Judy /delete
net user Rose /delete
net user Johnny /delete
net user Benjamin /delete
net user Joseph /delete
net user Charles /delete
net user Carol /delete
net user William /delete
net user Thomas /delete
net user James /delete
net user Daniel /delete
net user Alexander /delete
net user Aaron /delete
net user Rachel /delete
net user Rebecca /delete
net user Anna /delete
net user Kathy /delete
net user Kathleen /delete
net user Christine /delete
net user Judith /delete
net user Jonathan /delete
net user Stephanie /delete
net user Andrew /delete
net user Lori /delete
net user Philip /delete
net user Abigail /delete
net user Ryan /delete
net user Dorothy /delete
net user Richard /delete
net user Marie /delete
net user Angela /delete
net user Janice /delete
net user Jordan /delete
net user Dylan /delete
net user Samuel /delete
net user Janet /delete
net user Doris /delete
net user Paul /delete
net user Carolyn /delete
net user Melissa /delete
net user Elizabeth /delete
net user Susan /delete
net user Andrea /delete
net user Kathryn /delete
net user Tyler /delete
net user Linda /delete
net user Joan /delete
net user Christina /delete
net user Matthew /delete
net user Brittany /delete
net user Sharon /delete
net user Alice /delete
net user Nathan /delete
net user Edward /delete
net user Sean /delete
net user Beverly /delete
net user Denise /delete
net user Gary /delete
net user Virginia /delete
net user Terry /delete
net user Noah /delete
net user Cynthia /delete
net user Natalie /delete
net user Ann /delete
net user Arthur /delete
net user Michael /delete
net user Christopher /delete
net user Gregory /delete
net user Jack /delete
net user Dennis /delete
net user Jerry /delete
net user Joyce /delete
net user Shirley /delete
net user Betty /delete
net user Martha /delete
net user Mary /delete
net user Catherine /delete
net user Katherine /delete
net user Ethan /delete
net user Jeffrey /delete
net user Theresa /delete
net user Scott /delete
net user Pamela /delete
net user Peter /delete
net user Julia /delete
net user Sarah /delete
net user Roy /delete
net user Douglas /delete
net user Lauren /delete
net user Mildred /delete
net user Lisa /delete
net user Kevin /delete